Repository input-output-hk/chain-libs, pull requests merged in 2019-06, with the labels that each got.

#19 make the from_millis function a `const` function
  chain-impl-mockchain/src/milli.rs
Labels: enhancement

#20 keep travis to its minimal (check osx)
  .travis.yml
Labels: tests

#26 Remove num traits
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/block/header.rs
  chain-impl-mockchain/src/block/version.rs
  chain-impl-mockchain/src/certificate.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/message/mod.rs
  chain-impl-mockchain/src/utxo.rs
Labels: cleanup

#29 Property tests for address and ledger discrimination
  chain-impl-mockchain/tests/common/address.rs
  chain-impl-mockchain/tests/common/ledger.rs
  chain-impl-mockchain/tests/genesis/genesis_tests.rs
  chain-impl-mockchain/tests/ledger/discrimination_tests.rs
  chain-impl-mockchain/tests/ledger/ledger_tests.rs
  chain-impl-mockchain/tests/ledger/mod.rs
Labels: test

#30 Property test for initial transaction
  chain-addr/src/testing.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/testing/address.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/kind_type.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/output.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/tx_builder.rs
  chain-impl-mockchain/src/transaction/mod.rs
  chain-impl-mockchain/tests/genesis/genesis_tests.rs
  chain-impl-mockchain/tests/genesis/mod.rs
  chain-impl-mockchain/tests/tests.rs
Labels: test
