Repository input-output-hk/chain-libs, pull requests merged in 2019-09, with the labels that each got.

#83 [Tests] Property test for Transaction with Certificate builder
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/leader.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/txbuilder.rs
Labels: test

#89 FragmentService API for network protocol client
  network-core/src/client.rs
  network-core/src/client/content.rs
  network-grpc/src/client.rs
Labels: feature

#91 Ledger apply TX clean up
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/transaction/transaction.rs
Labels: cleanup, refactoring

#92 Work around a bug in futures::stream::Forward
  network-grpc/src/service.rs
Labels: bug

#94 Delayed resolution for upload sinks
  network-core/src/server/block.rs
  network-grpc/src/service.rs
Labels: breaking-change, enhancement

#97 Rename content to fragment, flatten chain-core public namespace
  network-core/src/client.rs
  network-core/src/client/fragment.rs
  network-core/src/server.rs
  network-core/src/server/fragment.rs
  network-grpc/proto/node.proto
  network-grpc/src/client.rs
  network-grpc/src/client/handshake.rs
  network-grpc/src/server.rs
  network-grpc/src/service.rs
Labels: breaking-change, refactoring

#96 add address design and implementation document
  chain-impl-mockchain/doc/address.md
Labels: design, doc

#95 Add incentive framework
  chain-impl-mockchain/doc/incentives.md
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/block/leaderlog.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/pots.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/multisig/ledger.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/treasury.rs
  chain-impl-mockchain/src/value.rs
  imhamt/src/hamt.rs
  imhamt/src/operation.rs
  typed-bytes/src/builder.rs
Labels: breaking-change, enhancement, epic

#61 [Tests] Property test: stake distribution is consistent
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
  chain-impl-mockchain/src/testing/data/address.rs
Labels: test

#85 [Tests] Ledger internals property tests
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/leader.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/transaction/transaction.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/utxo.rs
Labels: test

#63 [Tests] Added fee to property test: total_funds_are_total_in_ledger
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: test
