Repository input-output-hk/chain-libs, pull requests merged in 2019-12, with the labels that each got.

#184 LeaderLog didn't increase the value when calling `increase_for` in the Ledger::apply_block
  chain-impl-mockchain/src/block/leaderlog.rs
Labels: bug

#158 Add tag for utxo witness
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/transaction/witness.rs
Labels: breaking-change, enhancement, on hold, security

#185 fix double update of the stake distribution
  chain-impl-mockchain/src/stake/distribution.rs
Labels: bug

#179 [Tests] Pool registration - new test cases
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests.rs
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/e2e/management_threshold.rs
  chain-impl-mockchain/src/testing/e2e/mod.rs
  chain-impl-mockchain/src/testing/e2e/owner_delegation.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/mod.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-impl-mockchain/src/testing/scenario/template/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
Labels: test

#181 [Tests] initial funds overflow test
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
Labels: test

#189 [Tests] Delegation ratio tests
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/stake/stake.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
  chain-impl-mockchain/src/testing/e2e/mod.rs
  chain-impl-mockchain/src/testing/e2e/stake_distribution.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/value.rs
  sparse-array/src/fast.rs
Labels: test

#191 Add treasury tax getter to Rewards
  chain-impl-mockchain/src/rewards.rs
Labels: enhancement

#192 Reward fixes & status
  chain-impl-mockchain/doc/incentives.md
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/last_rewards.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/stake/stake.rs
  imhamt/src/hamt.rs
  imhamt/src/lib.rs
  imhamt/src/node/reference.rs
Labels: enhancement

#193 move accessor of the treasury tax to the new place
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/rewards.rs
Labels: bug

#194 Fix delegation rewards
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: bug

#196 Fix rustfmt for tests
  chain-crypto/src/testing.rs
  chain-impl-mockchain/src/fragment/content.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/pots.rs
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/macros.rs
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/keys.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/e2e/management_threshold.rs
  chain-impl-mockchain/src/testing/e2e/mod.rs
  chain-impl-mockchain/src/testing/e2e/stake_distribution.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/scenario/mod.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
  chain-impl-mockchain/src/testing/scenario/template/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/testing/verifiers/mod.rs
Labels: test

#197 Fix reward to delegators calculation
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/stake/stake.rs
Labels: bug

#198 revert invalid change
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: bug

#202 rewards: replace 'binary XOR' by the actually meant value
  chain-impl-mockchain/src/rewards.rs
Labels: bug

#166 Network client API improvements
  network-core/src/client/block.rs
  network-core/src/client/fragment.rs
  network-core/src/client/gossip.rs
  network-core/src/error.rs
  network-grpc/src/client.rs
  network-grpc/src/client/client_streaming.rs
  network-grpc/src/client/server_streaming.rs
  network-grpc/src/client/subscription.rs
  network-grpc/src/client/unary.rs
Labels: breaking-change, cleanup, enhancement

#201 Fix linear rewards reset to inintial after reduction to 0
  chain-impl-mockchain/src/rewards.rs
Labels: bug, high priority

#199 [Tests] Distribution rewards initial test cases
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/testing/e2e/mod.rs
  chain-impl-mockchain/src/testing/e2e/rewards.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/mod.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
  chain-impl-mockchain/src/testing/scenario/template/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
Labels: test

#200 Make reward params fields public
  chain-impl-mockchain/src/rewards.rs
Labels: enhancement

#204 Block Content Size and content hash verification
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/header/eval.rs
  chain-impl-mockchain/src/header/header.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: enhancement

#207 remove useless blockchain config parameter
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
Labels: enhancement

#208 expose epoch stability depth
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: enhancement

#206 [Tests] Rewards delegation tests
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/testing/e2e/rewards.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
  chain-impl-mockchain/src/testing/scenario/mod.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
Labels: test

#209 [Tests] Leadership rewards test
  chain-impl-mockchain/src/testing/e2e/rewards.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
Labels: test

#212 Add fees-to-treasury setting
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/setting.rs
Labels: high priority, test

#213 [Tests] Stake pool tax
  chain-impl-mockchain/src/testing/e2e/rewards/mod.rs
  chain-impl-mockchain/src/testing/e2e/rewards/tax.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
Labels: test

#216 attempt to distribute the rewards to delegator only if there are remaining rewards
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: optimisation

#217 Expose ledger pots
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: enhancement

#221 apply fees for owner stake delegation
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: bug

#222 [Tests] block max content negative test
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: test

#223 [Test]Account, leader log, rewards tests
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/last_rewards.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/block/leaderlog.rs
Labels: test

#220 [Tests] Per certificate fees
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/e2e/fees/mod.rs
  chain-impl-mockchain/src/testing/e2e/mod.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: test

#226 [Tests] owner/delegator of many stake pools
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/e2e/rewards/mod.rs
Labels: test

#227 [Tests] Header Builder and ledger tests
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/header/builder.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/data/leader.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/testing/mod.rs
Labels: test

#228 allow cloning the sqlite pool
  chain-storage-sqlite-old/src/lib.rs
Labels: high priority

#230 Handle EINVAL on setting TCP_NODELAY on Mac OS
  network-grpc/src/server.rs
Labels: bug
