Repository input-output-hk/chain-libs, pull requests merged in 2019-08, with the labels that each got.

#75 Switch from in-house hex to hex crate in chain-crypto
  chain-crypto/Cargo.toml
  chain-crypto/src/digest.rs
  chain-crypto/src/hash.rs
  chain-crypto/src/hex.rs
  chain-crypto/src/key.rs
  chain-crypto/src/lib.rs
  chain-crypto/src/sign.rs
Labels: cleanup

#73 [Tests] Enabled Property-test-api annotation for arbitraries
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/milli.rs
  chain-impl-mockchain/src/testing/address.rs
Labels: test

#74 [Tests] Property test for account ledger
  chain-impl-mockchain/src/accounting/account/mod.rs
Labels: test

#64 Certificate overhaul
  chain-core/src/mempack.rs
  chain-core/src/property.rs
  chain-crypto/Cargo.toml
  chain-crypto/src/digest.rs
  chain-crypto/src/sign.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/doc/format.md
  chain-impl-mockchain/src/account.rs
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/block/builder.rs
  chain-impl-mockchain/src/block/header.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/certificate.rs
  chain-impl-mockchain/src/certificate/delegation.rs
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/leadership/bft.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/mod.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/multisig/ledger.rs
  chain-impl-mockchain/src/multisig/witness.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/stake/mod.rs
  chain-impl-mockchain/src/stake/role.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/transaction/mod.rs
  chain-impl-mockchain/src/transaction/transaction.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/txbuilder.rs
  chain-impl-mockchain/src/update.rs
  chain-time/src/lib.rs
  chain-time/src/timeline.rs
  chain-time/src/units.rs
  typed-bytes/src/builder.rs
  typed-bytes/src/lib.rs
Labels: design, enhancement, epic, feature, security

#84 move ledger iterator into its own module
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
Labels: cleanup

#78 [Tests] Property test for account ledger
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
Labels: test

#76 [Tests] Block builder property test
  chain-impl-mockchain/src/block/builder.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
Labels: test

#86 network-grpc: Update tower-hyper to 0.1.1
  network-grpc/Cargo.toml
Labels: cleanup

#88 network: PushHeaders and UploadBlocks forward to Sink
  network-core/src/server/block.rs
  network-grpc/src/service.rs
Labels: breaking-change, refactoring

#87 add conversions from u32 to and from ChainLength
  chain-impl-mockchain/src/block/header.rs
Labels: enhancement
