Repository input-output-hk/chain-libs, pull requests merged in 2019-11, with the labels that each got.

#128 Transaction rework
  chain-core/src/mempack.rs
  chain-crypto/src/sign.rs
  chain-crypto/src/testing.rs
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/certificate/delegation.rs
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/info.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/macros.rs
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/proposal_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/keys.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/requests.rs
  chain-impl-mockchain/src/transaction/builder.rs
  chain-impl-mockchain/src/transaction/element.rs
  chain-impl-mockchain/src/transaction/input.rs
  chain-impl-mockchain/src/transaction/io.rs
  chain-impl-mockchain/src/transaction/mod.rs
  chain-impl-mockchain/src/transaction/payload.rs
  chain-impl-mockchain/src/transaction/transaction.rs
  chain-impl-mockchain/src/transaction/transfer.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/txbuilder.rs
  chain-impl-mockchain/src/utxo.rs
  chain-impl-mockchain/src/value.rs
  chain-time/src/era.rs
  imhamt/src/bitmap.rs
  imhamt/src/hamt.rs
  imhamt/src/node/reference.rs
  typed-bytes/src/lib.rs
Labels: breaking-change, cleanup, enhancement, security

#132 Add method for getting single UTxO output from ledger
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: feature

#137 Fix legacy address verification in ledger
  cardano-legacy-address/src/address.rs
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: bug

#136 small update on the typed-bytes library to rely more on standard API and compiler
  typed-bytes/src/builder.rs
  typed-bytes/src/lib.rs
Labels: cleanup

#138 remove non needed call to from_slice
  cardano-legacy-address/src/address.rs
Labels: test

#139 Pools state
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/stake/distribution.rs
Labels: cleanup

#141 Expose full delegation possibility in certificates
  chain-impl-mockchain/doc/format.md
  chain-impl-mockchain/src/account.rs
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/certificate/delegation.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/multisig/ledger.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
Labels: breaking-change, enhancement

#142 add format.abnf and overview.md
  chain-impl-mockchain/doc/format.abnf
  chain-impl-mockchain/doc/overview.md
Labels: design, doc

#143 Future proof fragment header to allow one spare byte after the type
  chain-impl-mockchain/doc/format.abnf
  chain-impl-mockchain/doc/format.md
  chain-impl-mockchain/src/fragment/mod.rs
Labels: breaking-change

#144 Ledger check cleanup
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: cleanup

#146 Pool permissions & operators
  chain-core/src/mempack.rs
  chain-impl-mockchain/doc/format.abnf
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  typed-bytes/src/builder.rs
Labels: breaking-change, design, enhancement

#147 make the fragment padding/type act like a u16 be and simplify grammar
  chain-impl-mockchain/doc/format.abnf
  chain-impl-mockchain/src/fragment/mod.rs
Labels: breaking-change

#149 Cleanup format, reward account & multisig accounts discrimination
  chain-core/src/mempack.rs
  chain-impl-mockchain/doc/format.abnf
  chain-impl-mockchain/src/certificate/delegation.rs
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/transaction/element.rs
  chain-impl-mockchain/src/transaction/input.rs
  chain-impl-mockchain/src/transaction/mod.rs
Labels: breaking-change, enhancement

#127 [Test] Initial builder refactor
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/cert_signer.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/testing/verifiers/mod.rs
Labels: test

#155 [Tests]Repair ledger tests
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/keys.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/transaction/element.rs
  chain-impl-mockchain/src/utxo.rs
Labels: test

#150 (#52) Optimize unspent utxo
  Cargo.toml
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/utxo.rs
  sparse-array/Cargo.toml
  sparse-array/src/bitmap.rs
  sparse-array/src/fast.rs
  sparse-array/src/lib.rs
  sparse-array/src/sparse_array.rs
Labels: enhancement

#125 [Tests] New test cases for Ledger::new method
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
Labels: test

#154 Optimise HAMT inner representation to use Box instead of Vec
  imhamt/Cargo.toml
  imhamt/examples/memdump/main.rs
  imhamt/examples/memdump/unix.rs
  imhamt/src/bitmap.rs
  imhamt/src/content.rs
  imhamt/src/hamt.rs
  imhamt/src/hash.rs
  imhamt/src/helper.rs
  imhamt/src/lib.rs
  imhamt/src/node/reference.rs
Labels: enhancement, optimisation

#122 [Tests] Scenario chain libs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/cert_signer.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/mod.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
  chain-impl-mockchain/src/testing/scenario/template/mod.rs
Labels: test

#168 Implement fees for different certificate types
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
Labels: enhancement

#171 fix test_internal_apply_transaction_is_balanced
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: test

#173 fix per certificate fee scheme
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/fee.rs
Labels: enhancement

#174 Fix encoding of the per certificate fee parameters
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/fee.rs
Labels: bug

#175 Incentive config
  chain-core/src/mempack.rs
  chain-impl-mockchain/doc/incentives.md
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/setting.rs
Labels: cleanup

#176 On some architecture, the get_first_index_impl fails to returns a valid value
  sparse-array/src/bitmap.rs
  sparse-array/src/fast.rs
Labels: bug
