Repository input-output-hk/chain-libs, pull requests merged in 2019-07, with the labels that each got.

#31 allow equality comparison between 2 certificates
  chain-impl-mockchain/src/certificate.rs
Labels: enhancement

#37 Warning removal in imhamt and chain-crypto
  chain-crypto/src/algorithms/sumed25519/sum.rs
  imhamt/src/lib.rs
Labels: cleanup

#40 network-core: turn BlockEvent::Missing into a named struct
  network-core/src/subscription.rs
  network-grpc/src/convert.rs
Labels: refactoring

#38 Address removal of environment prefix
  chain-addr/build.rs
  chain-addr/src/lib.rs
  chain-addr/src/testing.rs
  chain-impl-mockchain/src/transaction/transfer.rs
Labels: cleanup, enhancement

#33 [Tests] Property test: the blockchain state total value is constant
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/address.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/output.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/tx_builder.rs
  chain-impl-mockchain/src/transaction/transfer.rs
Labels: test

#43 CircleCI improvements
  .circleci/config.yml
Labels: test

#46 remove blake2b224
  chain-crypto/src/hash.rs
  chain-crypto/src/lib.rs
  chain-crypto/src/testing.rs
Labels: cleanup

#47 Add (somewhat) generic Digest type
  chain-crypto/src/digest.rs
  chain-crypto/src/lib.rs
Labels: design, enhancement

#48 Message to fragment rename
  chain-impl-mockchain/src/block/builder.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/fragment/config.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/fragment/raw.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/message/mod.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/tx_builder.rs
  chain-impl-mockchain/src/update.rs
Labels: cleanup

#44 network: Change header push API to remove a generic
  network-core/src/error.rs
  network-core/src/server/block.rs
  network-grpc/src/convert.rs
  network-grpc/src/service.rs
Labels: refactoring

#50 Role crypto
  chain-crypto/src/digest.rs
  chain-crypto/src/lib.rs
  chain-crypto/src/role.rs
  chain-crypto/src/testing.rs
Labels: enhancement

#45 Added verification for account states for 'total_funds' property test
  chain-addr/src/lib.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/address.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/utxo.rs
Labels: test

#56 Transaction-ID removal
  chain-impl-mockchain/doc/format.md
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/legacy.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/transaction/transaction.rs
  chain-impl-mockchain/src/transaction/transfer.rs
  chain-impl-mockchain/src/transaction/utxo.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/txbuilder.rs
  chain-impl-mockchain/src/utxo.rs
Labels: breaking-change, enhancement, high priority, security

#57 [Tests] Property tests: voting and proposals
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/update.rs
Labels: test

#60 replace ... by ..= in hex
  chain-crypto/src/hex.rs
Labels: cleanup

#59 [Tests] Utxo verification for test: total_funds_are_total_in_ledger
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
Labels: test

#58 chain-core, network: Rename Message to Fragment
  chain-core/src/property.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/multiverse.rs
  network-core/src/server/content.rs
  network-grpc/proto/node.proto
  network-grpc/src/convert.rs
  network-grpc/src/server.rs
  network-grpc/src/service.rs
Labels: breaking-change, refactoring

#67 [Tests] Added property tests for account state.
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
Labels: test

#42 [Tests] Property test: leader election is consistent with the stake
  chain-impl-mockchain/src/leadership/genesis/mod.rs
Labels: test

#70 add typed-bytes
  Cargo.toml
  typed-bytes/Cargo.toml
  typed-bytes/LICENSE-APACHE
  typed-bytes/LICENSE-MIT
  typed-bytes/src/lib.rs
Labels: cleanup, feature

#69 add ABOR
  chain-core/src/abor.rs
  chain-core/src/lib.rs
Labels: cleanup, feature

#66 network: Add Handshake method
  network-core/src/client/block.rs
  network-core/src/server/block.rs
  network-grpc/proto/node.proto
  network-grpc/src/client.rs
  network-grpc/src/client/handshake.rs
  network-grpc/src/lib.rs
  network-grpc/src/service.rs
Labels: feature

#65 [Tests] Address data enhancement
  chain-crypto/src/testing.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/testing/address.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/tx_builder.rs
Labels: test

#62 [Tests] Introduced cert builder
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
Labels: test
