Repository input-output-hk/chain-libs, pull requests merged in 2019-10, with the labels that each got.

#101 network-grpc: Update tower dependencies
  network-grpc/Cargo.toml
Labels: enhancement

#77 [Tests] Test data builders
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/proposal_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/requests.rs
  chain-impl-mockchain/src/update.rs
Labels: test

#104 remove usage of unwrap where possible
  chain-storage-sqlite/src/lib.rs
  chain-storage/src/error.rs
Labels: enhancement

#106 Lower level error accessors for ConnectError
  network-grpc/src/client/connect.rs
Labels: enhancement

#108 timeframe: add slot duration retrieval
  chain-time/src/timeframe.rs
Labels: enhancement

#109 Ignore per-connection listener errors
  network-grpc/src/server.rs
Labels: bug, enhancement, refactoring

#107 [Tests] verify and leader methods in LeadershipData struct
  chain-impl-mockchain/src/leadership/bft.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-time/src/timeframe.rs
Labels: test

#110 Document return value of BlockStore::is_ancestor
  chain-storage/src/store.rs
Labels: doc

#100 Apply empty block prop test
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/block/header.rs
  chain-impl-mockchain/src/leadership/genesis/vrfeval.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/pots.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/treasury.rs
  chain-time/Cargo.toml
  chain-time/src/era.rs
  chain-time/src/lib.rs
  chain-time/src/testing.rs
Labels: test

#103 Property test for DelegationState struct
  chain-impl-mockchain/src/stake/delegation.rs
Labels: test

#105 Test data builders - old utxo builder & cert builder
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/old_address_builder.rs
Labels: test

#114 Header prepare
  chain-core/src/mempack.rs
  chain-crypto/src/algorithms/vrf/mod.rs
  chain-crypto/src/algorithms/vrf/vrf.rs
  chain-crypto/src/bech32.rs
  chain-crypto/src/digest.rs
  chain-crypto/src/hash.rs
  chain-crypto/src/sign.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/block/builder.rs
  chain-impl-mockchain/src/block/content.rs
  chain-impl-mockchain/src/block/cstruct.rs
  chain-impl-mockchain/src/block/header.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/block/version.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/transaction/transaction.rs
  chain-impl-mockchain/src/update.rs
  typed-bytes/src/builder.rs
Labels: cleanup

#115 Header refactor
  chain-impl-mockchain/src/block/builder.rs
  chain-impl-mockchain/src/block/cstruct.rs
  chain-impl-mockchain/src/block/header.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/block/version.rs
  chain-impl-mockchain/src/fragment/content.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/header/builder.rs
  chain-impl-mockchain/src/header/components.rs
  chain-impl-mockchain/src/header/cstruct.rs
  chain-impl-mockchain/src/header/deconstruct.rs
  chain-impl-mockchain/src/header/eval.rs
  chain-impl-mockchain/src/header/header.rs
  chain-impl-mockchain/src/header/mod.rs
  chain-impl-mockchain/src/header/version.rs
  chain-impl-mockchain/src/leadership/bft.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/mod.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/update.rs
Labels: breaking-change, enhancement, optimisation, security

#81 [Tests] Fix for #79. Added property & negative tests for update module
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/update_builder.rs
  chain-impl-mockchain/src/testing/data/leader.rs
  chain-impl-mockchain/src/update.rs
Labels: test

#117 Grace parameter update for leader election test
  chain-impl-mockchain/src/leadership/genesis/mod.rs
Labels: test

#112 [Tests] Transaction tests cases for gaps in automation
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/ledger/tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/testing/data/address.rs
Labels: test

#120 Fix CBOR (de)serialization for legacy ExtendedAddr
  cardano-legacy-address/src/address.rs
Labels: bug

#121 [Tests] small test code refactor
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/mod.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/mod.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/requests.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/testing/verifiers/mod.rs
Labels: test

#124 Implement old UTXO witness creation and verification
  chain-impl-mockchain/src/transaction/witness.rs
Labels: cleanup, enhancement

#126 network: Rework inbound stream processing for server
  network-core/Cargo.toml
  network-core/src/server.rs
  network-core/src/server/block.rs
  network-core/src/server/fragment.rs
  network-core/src/server/gossip.rs
  network-core/src/server/request_stream.rs
  network-grpc/src/service.rs
  network-grpc/src/service/request_stream.rs
  network-grpc/src/service/response_future.rs
  network-grpc/src/service/response_stream.rs
  network-grpc/src/service/subscription.rs
Labels: cleanup, enhancement, refactoring

#129 Use a self-descriptive enum in Subscription
  network-grpc/src/service/subscription.rs
Labels: refactoring

#131 Fix UTxO iterator overflowing
  chain-impl-mockchain/src/utxo.rs
Labels: bug
