Repository input-output-hk/chain-libs, pull requests merged in 2020-01, with the labels that each got.

#229 [Tests] compilation fix for property-test-api feature
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/account.rs
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/accounting/account/test.rs
  chain-impl-mockchain/src/block/header.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/date.rs
  chain-impl-mockchain/src/fragment/config.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/header/header.rs
  chain-impl-mockchain/src/header/mod.rs
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/mod.rs
  chain-impl-mockchain/src/leadership/test.rs
  chain-impl-mockchain/src/legacy.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/transaction/input.rs
  chain-impl-mockchain/src/transaction/mod.rs
  chain-impl-mockchain/src/transaction/test.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/update.rs
Labels: test

#234 update dependencies
  chain-addr/Cargo.toml
  chain-core/Cargo.toml
  chain-crypto/Cargo.toml
  chain-crypto/src/algorithms/vrf/dleq.rs
  chain-crypto/src/algorithms/vrf/vrf.rs
  chain-crypto/src/asymlock.rs
  chain-crypto/src/testing.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/genesis/vrfeval.rs
  chain-impl-mockchain/src/leadership/test.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/testing/builders/old_address_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/transaction/test.rs
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/src/lib.rs
  chain-storage-sqlite/Cargo.toml
  chain-storage-sqlite/src/lib.rs
  chain-storage/Cargo.toml
  chain-storage/src/memory.rs
  chain-time/Cargo.toml
  imhamt/Cargo.toml
  sparse-array/Cargo.toml
Labels: cleanup

#235 Change listeners API to yield the remote socket address
  network-grpc/Cargo.toml
  network-grpc/src/server.rs
Labels: breaking-change, enhancement

#236 Update rand_chacha dep
  chain-impl-mockchain/Cargo.toml
Labels: cleanup

#237 Merge pull request #237 from input-output-hk/safer-sqlite-block-store
  chain-storage-sqlite-old/src/lib.rs
Labels: breaking-change, design, enhancement

#242 rename the `new` function to `with_executor` and implement new `new` with default executor
  network-grpc/Cargo.toml
  network-grpc/src/client/connect.rs
Labels: breaking-change

#232 allow cloning the sqlite pool in new impl
  chain-storage-sqlite/src/lib.rs
Labels: enhancement

#243 use path instead of open option for in-memory sqlite
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/src/lib.rs
Labels: bug

#238 benchmarks for sqlite storage
  .gitignore
  chain-core/src/packer.rs
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/benches/storage.rs
  chain-storage/src/store.rs
Labels: bench

#211 add windows and mac to github workflow
  .github/workflows/main.yml
Labels: test

#245 fix sqlite DatabaseLocked
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/src/lib.rs
Labels: bug

#246 [Tests] refactored FragmentFactory and certs builders
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
Labels: test

#244 network-core: More detailed Display impl for Error
  network-core/src/error.rs
Labels: enhancement

#247 storage: put_block error if block exists
  chain-storage/src/store.rs
Labels: breaking-change, enhancement

#248 add a short header description capability header.description()
  chain-impl-mockchain/src/header/header.rs
Labels: enhancement

#250 replace blockid&property by `HeaderId`
  chain-impl-mockchain/src/multiverse.rs
Labels: cleanup
