Repository input-output-hk/chain-libs, pull requests merged in 2020-05, with the labels that each got.

#365 add support for script address
  chain-addr/src/lib.rs
  chain-addr/src/testing.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/testing/arbitrary/kind_type.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/keys.rs
Labels: Smart Contract, enhancement

#366 [Tests] Vote plan manager test
  chain-impl-mockchain/src/certificate/vote_cast.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/testing/gen/mod.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/vote/manager.rs
Labels: VOTE, test

#367 Make rustfmt use in tonic-build optional during builds
  chain-network/Cargo.toml
Labels: cleanup, update-deps

#368 API to encode public address in subscription requests
  chain-network/src/grpc/client.rs
  chain-network/src/grpc/convert.rs
Labels: feature

#369 made vote finish exclusive
  chain-impl-mockchain/src/certificate/vote_plan.rs
Labels: VOTE, bug, test

#373 chain-core remove of property-test-api
  Cargo.toml
  chain-core/Cargo.toml
  chain-core/src/lib.rs
  chain-core/src/property.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/transaction/test.rs
  chain-impl-mockchain/src/update.rs
  chain-test-utils/Cargo.toml
  chain-test-utils/src/lib.rs
  chain-test-utils/src/property/mod.rs
Labels: cleanup, refactoring

#375 Fix deps for missing new chain-test-utils
  chain-impl-mockchain/Cargo.toml
Labels: bug

#380 Improve Debug formatting of BlockId and FragmentId
  chain-network/src/data/block/id.rs
  chain-network/src/data/fragment/id.rs
Labels: enhancement

#379 Fix compilation of benchmarks & remove unimplemented feature from imhamt
  cardano-legacy-address/Cargo.toml
  cardano-legacy-address/benches/cbor.rs
  cardano-legacy-address/src/cbor.rs
  cardano-legacy-address/src/lib.rs
  chain-crypto/Cargo.toml
  chain-crypto/benches/sumed25519.rs
  chain-crypto/benches/vrf.rs
  chain-crypto/src/algorithms/mod.rs
  chain-crypto/src/algorithms/sumed25519/mod.rs
  chain-crypto/src/algorithms/sumed25519/sum.rs
  chain-crypto/src/algorithms/vrf/vrf.rs
  chain-crypto/src/lib.rs
  chain-storage/src/lib.rs
  imhamt/Cargo.toml
  imhamt/benches/imhamt.rs
  imhamt/src/lib.rs
  imhamt/src/node/mod.rs
  imhamt/src/node/optimized.rs
Labels: bench, cleanup

#370 Minor network API refinements
  chain-network/src/core/server/node.rs
  chain-network/src/grpc/server.rs
Labels: cleanup, refactoring

#377 [Test] Test scenarios for vote plan & vote cast
  chain-impl-mockchain/src/ledger/tests/certificate_tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/voting.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
Labels: test

#386 add bft leader id getter
  chain-impl-mockchain/src/header/header.rs
Labels: enhancement

#383 GitHub CI improvements
  .github/workflows/main.yml
Labels: CI

#389 remove all unused imports...
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/date.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/milli.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/transaction/test.rs
  chain-impl-mockchain/src/update.rs
  chain-impl-mockchain/src/vote/committee.rs
Labels: cleanup

#390 fix export for the jomungandr dependency
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
Labels: cleanup

#391 Clippy 0 warning allowed
  .github/workflows/main.yml
  btree/benches/benchmark.rs
  btree/examples/blockindex.rs
  btree/src/arrayview.rs
  btree/src/btreeindex/backtrack.rs
  btree/src/btreeindex/mod.rs
  btree/src/btreeindex/node/internal_node.rs
  btree/src/btreeindex/node/leaf_node.rs
  btree/src/btreeindex/node/mod.rs
  btree/src/btreeindex/pages.rs
  btree/src/lib.rs
  btree/src/storage.rs
  cardano-legacy-address/benches/cbor.rs
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/error.rs
  chain-impl-mockchain/src/leadership/mod.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-network/src/data/block/mod.rs
  chain-network/src/data/fragment/mod.rs
  chain-network/src/grpc/convert.rs
  chain-storage/benches/storage.rs
Labels: CI, cleanup

#388 Add timeout to GitHub CI test jobs
  .github/workflows/main.yml
Labels: CI

#392 Voting Plan update: allow for different kind of payloads to be submitted
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_cast.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/vote/choice.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/mod.rs
  chain-impl-mockchain/src/vote/payload.rs
Labels: VOTE, enhancement

#393 enable some vote related functionality
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: VOTE, enhancement
