Repository input-output-hk/chain-libs, pull requests merged in 2020-09, with the labels that each got.

#447 remove dbg statements
  btree/src/btreeindex/mod.rs
  chain-impl-mockchain/src/block/headerraw.rs
  chain-ser/src/mempack.rs
Labels: cleanup

#448 [Tests] vote manager tests
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/tally.rs
Labels: test

#446 Remove tests on nightly Rust from CircleCI
  .circleci/config.yml
Labels: CI, cleanup

#423 remove dead code
  chain-impl-mockchain/src/environment.rs
  chain-impl-mockchain/src/lib.rs
Labels: cleanup

#385 chain-storage: sled migration + permanent store
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/multiverse.rs
  chain-storage/Cargo.toml
  chain-storage/README.md
  chain-storage/benches/storage.rs
  chain-storage/src/block_info.rs
  chain-storage/src/block_store.rs
  chain-storage/src/error.rs
  chain-storage/src/index.rs
  chain-storage/src/iterator.rs
  chain-storage/src/lib.rs
  chain-storage/src/permanent_store.rs
  chain-storage/src/test_utils.rs
  chain-storage/src/tests.rs
  chain-storage/src/value.rs
Labels: breaking-change

#451 Fix fmt in mockchain
  chain-impl-mockchain/src/lib.rs
Labels: cleanup

#456 Encrypted Voting
  Cargo.toml
  chain-vote/Cargo.toml
  chain-vote/benches/gmul.rs
  chain-vote/benches/shvzk.rs
  chain-vote/src/commitment.rs
  chain-vote/src/committee.rs
  chain-vote/src/encrypted.rs
  chain-vote/src/gang/mod.rs
  chain-vote/src/gang/p256k1.rs
  chain-vote/src/gang/zerocaf.rs
  chain-vote/src/gargamel.rs
  chain-vote/src/hybrid.rs
  chain-vote/src/lib.rs
  chain-vote/src/math.rs
  chain-vote/src/shvzk.rs
  chain-vote/src/unit_vector.rs
Labels: crypto

#455 [Test] added block/header ser/deser tests
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
Labels: test
