Repository input-output-hk/chain-libs, pull requests merged in 2020-06, with the labels that each got.

#394 gRPC: Support legacy "node-id-bin" metadata
  chain-network/Cargo.toml
  chain-network/src/grpc/client.rs
  chain-network/src/grpc/legacy.rs
  chain-network/src/grpc/mod.rs
  chain-network/src/grpc/server.rs
  chain-network/src/lib.rs
Labels: feature, legacy

#387 Fix and improve caching in GitHub CI
  .github/workflows/main.yml
Labels: CI

#384 CircleCI improvements
  .circleci/config.yml
Labels: CI, cleanup

#396 Fix clippy lints in mockchain
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/update.rs
  chain-impl-mockchain/src/utxo.rs
Labels: cleanup

#395 Fix the length of legacy node IDs
  chain-network/src/grpc/legacy.rs
Labels: bug, legacy

#398 Make cargo fmt fast again
  .github/workflows/main.yml
Labels: CI

#397 Disable incremental compilation in GitHub CI
  .github/workflows/main.yml
Labels: CI

#399 Don't use --all flag with cargo fmt
  .github/workflows/main.yml
Labels: CI

#405 Fix btree clippy warnings
  btree/src/arrayview.rs
  btree/src/btreeindex/backtrack.rs
  btree/src/btreeindex/mod.rs
  btree/src/btreeindex/node/internal_node.rs
  btree/src/btreeindex/node/leaf_node.rs
  btree/src/lib.rs
  btree/src/storage.rs
Labels: cleanup

#404 Automatically tally votes on chain if the votes are public
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_tally.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
  chain-impl-mockchain/src/vote/committee.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/mod.rs
  chain-impl-mockchain/src/vote/status.rs
  chain-impl-mockchain/src/vote/tally.rs
Labels: VOTE, enhancement

#409 GitHub CI: Work around special caching on Windows
  .github/workflows/main.yml
Labels: CI

#408 Reserve a branch for CI testing
  .github/workflows/main.yml
Labels: CI

#413 Improve debugging facilities of legacy node IDs
  chain-network/src/grpc/legacy.rs
Labels: enhancement, legacy

#414 Add conversion to legacy node ID from byte slices
  chain-network/src/grpc/legacy.rs
Labels: enhancement, legacy

#412 Extend who is committee members
  btree/benches/benchmark.rs
  btree/src/btreeindex/mod.rs
  btree/src/lib.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/certificate/vote_tally.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/keys.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
  chain-impl-mockchain/src/testing/scenario/template/mod.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/utxo.rs
  chain-impl-mockchain/src/vote/committee.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
  imhamt/src/lib.rs
Labels: VOTE

#415 VotePlan certificate authentication
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/voting.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
Labels: VOTE, breaking-change, enhancement

#416 Vote action
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/ledger/governance/mod.rs
  chain-impl-mockchain/src/ledger/governance/treasury.rs
  chain-impl-mockchain/src/ledger/info.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/pots.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/voting.rs
  chain-impl-mockchain/src/stake/controlled.rs
  chain-impl-mockchain/src/stake/mod.rs
  chain-impl-mockchain/src/stake/stake.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/treasury.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/tally.rs
Labels: VOTE

#420 add checks on the governance acceptance criteria
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/ledger/governance/mod.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
Labels: bug
