Repository input-output-hk/chain-libs, pull requests merged in 2020-03, with the labels that each got.

#283 implement get_block_by_chain_height
  chain-storage-sqlite-old/src/lib.rs
Labels: enhancement

#293 allow to set storage busy timeout
  chain-storage-sqlite-old/benches/storage.rs
  chain-storage-sqlite-old/src/lib.rs
Labels: breaking-change, enhancement

#298 [Tests] Added missing test cases in chain libs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/testing/e2e/rewards/mod.rs
Labels: test

#300 remove sha3 re-export and update to cryptoxide-0.2
  chain-crypto/Cargo.toml
  chain-crypto/src/digest.rs
  chain-crypto/src/hash.rs
  chain-crypto/src/lib.rs
  chain-crypto/src/testing.rs
Labels: update-deps

#302 missing cryptoxide dependencies update
  cardano-legacy-address/Cargo.toml
  cardano-legacy-address/src/address.rs
  chain-addr/Cargo.toml
Labels: crypto, enhancement, update-deps

#305 Tidy ledger
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/last_rewards.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/chaineval.rs
  chain-impl-mockchain/src/chaintypes.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/header/builder.rs
  chain-impl-mockchain/src/header/components.rs
  chain-impl-mockchain/src/header/deconstruct.rs
  chain-impl-mockchain/src/header/header.rs
  chain-impl-mockchain/src/header/mod.rs
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/header/version.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/leadership/bft.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/genesis/vrfeval.rs
  chain-impl-mockchain/src/leadership/mod.rs
  chain-impl-mockchain/src/leadership/test.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/leaderlog.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/proposal_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/update_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/leader.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/mod.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/update.rs
Labels: refactoring

#306 [Tests] stake distribution test and leadership test
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/stake/stake.rs
  chain-impl-mockchain/src/testing/e2e/stake_distribution.rs
Labels: test

#308 arbitrary Ledger and TestLedger implementation
  chain-impl-mockchain/src/testing/arbitrary/config_builder.rs
  chain-impl-mockchain/src/testing/arbitrary/ledger_builder.rs
  chain-impl-mockchain/src/testing/arbitrary/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/wallet.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: test
