Repository input-output-hk/chain-libs, pull requests merged in 2020-02, with the labels that each got.

#186 Starting removing ed25519 bip32 for direct use
  cardano-legacy-address/Cargo.toml
  cardano-legacy-address/src/address.rs
  chain-crypto/Cargo.toml
  chain-crypto/src/algorithms/ed25519.rs
  chain-crypto/src/algorithms/ed25519_derive.rs
  chain-crypto/src/algorithms/ed25519_extended.rs
  chain-crypto/src/key.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/legacy.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/builders/old_address_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/transaction/element.rs
  chain-impl-mockchain/src/transaction/test.rs
  chain-impl-mockchain/src/transaction/witness.rs
Labels: cleanup, refactoring, update-deps

#277 add Display for EpochPosition and a From between EpochPosition to Blockdate
  chain-impl-mockchain/src/date.rs
  chain-time/src/era.rs
Labels: cleanup

#239 require explicit sqlite connections creation
  chain-storage-sqlite-old/src/lib.rs
Labels: breaking-change, design, enhancement

#278 Move all serializers to chain_ser breaking the chain_core property dependency
  Cargo.toml
  chain-core/Cargo.toml
  chain-core/src/lib.rs
  chain-core/src/property.rs
  chain-ser/Cargo.toml
  chain-ser/src/abor.rs
  chain-ser/src/deser.rs
  chain-ser/src/lib.rs
  chain-ser/src/mempack.rs
  chain-ser/src/packer.rs
Labels: cleanup

#218 Pool update
  chain-impl-mockchain/doc/format.abnf
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/stake/distribution.rs
Labels: design, enhancement

#280 bech32 upgrade
  chain-addr/Cargo.toml
  chain-addr/src/lib.rs
  chain-crypto/Cargo.toml
  chain-crypto/src/bech32.rs
Labels: update-deps

#275 Lockless Multiverse
  chain-impl-mockchain/src/header/components.rs
  chain-impl-mockchain/src/multiverse.rs
Labels: breaking-change, enhancement

#240 Prepare to remove the BlockStore trait
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/benches/storage.rs
  chain-storage-sqlite-old/src/lib.rs
Labels: breaking-change, design, enhancement

#285 Pool update disallow fees change
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/rewards.rs
Labels: chain

#290 Bump rusqlite version
  Cargo.toml
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/src/lib.rs
Labels: update-deps
