Repository input-output-hk/chain-libs, pull requests merged in 2020-04, with the labels that each got.

#312 add Multi asymmetric locked data primitive
  chain-crypto/src/lib.rs
  chain-crypto/src/multilock.rs
Labels: crypto

#317 make the value impl `std::iter::Sum`
  chain-impl-mockchain/src/value.rs
Labels: enhancement

#318 only import quickcheck-macros if needed
  chain-time/src/lib.rs
Labels: cleanup

#320 add Hash impl for the Addr object
  cardano-legacy-address/src/address.rs
Labels: enhancement

#333 encode cbor in cbor the haskell address format
  cardano-legacy-address/src/address.rs
Labels: bug

#332 [Tests] Pool update tests
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/mod.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_registration.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_update.rs
  chain-impl-mockchain/src/testing/builders/cert_builder.rs
  chain-impl-mockchain/src/testing/builders/initial_builder.rs
  chain-impl-mockchain/src/testing/data/stake_pool.rs
  chain-impl-mockchain/src/testing/e2e/mod.rs
  chain-impl-mockchain/src/testing/e2e/pool_update.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
Labels: test

#335 remove the need for the property test api on this
  chain-impl-mockchain/src/ledger/iter.rs
Labels: cleanup, high priority

#334 [VIT] Vote plan certificate
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
Labels: VOTE, feature

#337 add extra fee settings to cover for the vote plan publishing
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/testing/e2e/fees/mod.rs
Labels: enhancement

#340 addvote cast certificate
  chain-impl-mockchain/src/certificate/mod.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_cast.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/fragment/test.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
Labels: enhancement

#342 vote/committee and initial config declaration
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/lib.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/vote/committee.rs
  chain-impl-mockchain/src/vote/mod.rs
Labels: enhancement

#343 Fix per vote fee settings
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/e2e/fees/mod.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/vote/committee.rs
Labels: bug

#338 [Tests] Small utils for changes in libs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/mod.rs
Labels: test

#344 mockchain - ledger, add committees to LedgerSettings
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: VOTE, enhancement

#297 cleanup chain-storage
  Cargo.toml
  chain-impl-mockchain/src/multiverse.rs
  chain-storage-sqlite-old/Cargo.toml
  chain-storage-sqlite-old/src/lib.rs
  chain-storage-sqlite/Cargo.toml
  chain-storage-sqlite/src/index.rs
  chain-storage-sqlite/src/lib.rs
  chain-storage/Cargo.toml
  chain-storage/benches/storage.rs
  chain-storage/src/error.rs
  chain-storage/src/index.rs
  chain-storage/src/lib.rs
  chain-storage/src/memory.rs
  chain-storage/src/store.rs
Labels: breaking-change, cleanup

#345 Vote plan management: plug in the blockchain ledger
  chain-impl-mockchain/src/certificate/vote_cast.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/ledger/info.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/mod.rs
Labels: VOTE, enhancement

#348 Vote cast management
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
Labels: VOTE, chain, enhancement

#347 Ledger recovery vote plan support
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/vote/ledger.rs
Labels: VOTE, enhancement

#350 chain-storage is not needed in the chain-impl-mockchain
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/multiverse.rs
Labels: cleanup, high priority, update-deps

#351 Deep cleanup
  btree/src/btreeindex/metadata.rs
  chain-core/src/property.rs
  chain-crypto/src/algorithms/sumed25519/sumrec.rs
  chain-crypto/src/algorithms/vrf/vrf.rs
  chain-crypto/src/hash.rs
  chain-impl-mockchain/src/block/mod.rs
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/chaintypes.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/date.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/legacy.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/rewards.rs
  chain-impl-mockchain/src/setting.rs
  chain-impl-mockchain/src/testing/scenario/template/mod.rs
  chain-impl-mockchain/src/transaction/builder.rs
  chain-impl-mockchain/src/transaction/payload.rs
  chain-impl-mockchain/src/treasury.rs
  chain-impl-mockchain/src/update.rs
Labels: cleanup

#354 Cleanup some warnings in typedbyte and chain-crypto
  chain-crypto/src/algorithms/ed25519_derive.rs
  chain-crypto/src/algorithms/sumed25519/common.rs
  chain-crypto/src/algorithms/sumed25519/sum.rs
  chain-crypto/src/algorithms/sumed25519/sumrec.rs
  chain-crypto/src/algorithms/vrf/dleq.rs
  chain-crypto/src/algorithms/vrf/mod.rs
  chain-crypto/src/algorithms/vrf/vrf.rs
  chain-crypto/src/asymlock.rs
  chain-crypto/src/bech32.rs
  chain-crypto/src/digest.rs
  chain-crypto/src/multilock.rs
  chain-crypto/src/role.rs
  chain-crypto/src/testing.rs
  typed-bytes/src/builder.rs
Labels: cleanup

#355 imhamt pass cleanup
  imhamt/src/bitmap.rs
  imhamt/src/hamt.rs
  imhamt/src/hash.rs
  imhamt/src/lib.rs
  imhamt/src/node/reference.rs
Labels: cleanup

#356 clippy on sparse-array
  sparse-array/src/bitmap.rs
  sparse-array/src/fast.rs
  sparse-array/src/sparse_array.rs
Labels: cleanup

#357 clippy cleanup of legacyaddress, chain-addr and chain-time
  cardano-legacy-address/src/address.rs
  cardano-legacy-address/src/base58.rs
  cardano-legacy-address/src/crc32.rs
  chain-addr/src/lib.rs
  chain-addr/src/testing.rs
  chain-time/src/era.rs
  chain-time/src/timeframe.rs
Labels: cleanup

#358 pass clippy on chain-storage
  chain-storage/src/index.rs
  chain-storage/src/lib.rs
Labels: breaking-change, cleanup

#359 cleanup chain-ser
  chain-ser/src/abor.rs
  chain-ser/src/mempack.rs
  chain-ser/src/packer.rs
Labels: cleanup

#360 cleanup in chain-impl-mockchain
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/certificate/delegation.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/config.rs
  chain-impl-mockchain/src/fee.rs
  chain-impl-mockchain/src/fragment/mod.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/genesis/vrfeval.rs
  chain-impl-mockchain/src/leadership/mod.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/leaderlog.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/reward_info.rs
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/milli.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/kind_type.rs
  chain-impl-mockchain/src/testing/arbitrary/ledger_builder.rs
  chain-impl-mockchain/src/testing/arbitrary/output.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/arbitrary/update_proposal.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/builders/proposal_builder.rs
  chain-impl-mockchain/src/testing/builders/stake_pool_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/builders/tx_cert_builder.rs
  chain-impl-mockchain/src/testing/builders/update_builder.rs
  chain-impl-mockchain/src/testing/builders/witness_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/e2e/fees/mod.rs
  chain-impl-mockchain/src/testing/e2e/management_threshold.rs
  chain-impl-mockchain/src/testing/e2e/pool_update.rs
  chain-impl-mockchain/src/testing/e2e/rewards/mod.rs
  chain-impl-mockchain/src/testing/e2e/rewards/tax.rs
  chain-impl-mockchain/src/testing/e2e/stake_distribution.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
  chain-impl-mockchain/src/transaction/builder.rs
  chain-impl-mockchain/src/transaction/input.rs
  chain-impl-mockchain/src/transaction/io.rs
  chain-impl-mockchain/src/transaction/mod.rs
  chain-impl-mockchain/src/transaction/payload.rs
  chain-impl-mockchain/src/transaction/transaction.rs
  chain-impl-mockchain/src/transaction/witness.rs
  chain-impl-mockchain/src/utxo.rs
  chain-impl-mockchain/src/value.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
Labels: cleanup

#361 Deep cleanup on impl-mockchain
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/accounting/account/account_state.rs
  chain-impl-mockchain/src/accounting/account/mod.rs
  chain-impl-mockchain/src/block/test.rs
  chain-impl-mockchain/src/certificate/delegation.rs
  chain-impl-mockchain/src/certificate/pool.rs
  chain-impl-mockchain/src/certificate/test.rs
  chain-impl-mockchain/src/certificate/vote_cast.rs
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/fragment/config.rs
  chain-impl-mockchain/src/fragment/content.rs
  chain-impl-mockchain/src/header/builder.rs
  chain-impl-mockchain/src/header/cstruct.rs
  chain-impl-mockchain/src/header/header.rs
  chain-impl-mockchain/src/header/mod.rs
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/leadership/genesis/vrfeval.rs
  chain-impl-mockchain/src/ledger/leaderlog.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/ledger/pots.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/ledger/reward_info.rs
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_registration.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_update.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/multisig/declaration.rs
  chain-impl-mockchain/src/multisig/index.rs
  chain-impl-mockchain/src/multisig/ledger.rs
  chain-impl-mockchain/src/multisig/mod.rs
  chain-impl-mockchain/src/multisig/witness.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/stake/delegation.rs
  chain-impl-mockchain/src/stake/distribution.rs
  chain-impl-mockchain/src/stake/mod.rs
  chain-impl-mockchain/src/stake/stake.rs
  chain-impl-mockchain/src/testing/builders/block_builder.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/update.rs
  chain-impl-mockchain/src/value.rs
  chain-ser/src/mempack.rs
  imhamt/examples/memdump/unix.rs
Labels: cleanup

#362 update CI to run the clippy check
  .github/workflows/main.yml
  btree/src/btreeindex/iter.rs
  btree/src/btreeindex/mod.rs
  btree/src/btreeindex/node/internal_node.rs
  btree/src/btreeindex/node/leaf_node.rs
  btree/src/btreeindex/pages.rs
  btree/src/btreeindex/version_management/mod.rs
  btree/src/btreeindex/version_management/transaction.rs
  btree/src/flatfile.rs
  btree/src/lib.rs
Labels: test

#363 [Test] Pool registration no update
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_update.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/arbitrary/utils.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/e2e/pool_update.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/scenario/fragment_factory.rs
  chain-impl-mockchain/src/testing/scenario/template/builders.rs
Labels: test

#364 unit tests for vote plan & proposals
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/testing/mod.rs
Labels: test
