Repository input-output-hk/chain-libs, pull requests merged in 2020-11, with the labels that each got.

#480 Expose serialization API for ProofOfCorrectVote
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/mod.rs
  chain-impl-mockchain/src/vote/payload.rs
  typed-bytes/src/lib.rs
Labels: breaking-change, enhancement

#481 Implemented encrypt_vote wrapper
  chain-impl-mockchain/src/vote/mod.rs
  chain-impl-mockchain/src/vote/payload.rs
  chain-impl-mockchain/src/vote/privacy.rs
Labels: enhancement

#482 Outer build warnings cleaning
  chain-impl-mockchain/src/block/test.rs
Labels: cleanup

#484 Block version test fixes
  chain-impl-mockchain/src/header/test.rs
  chain-impl-mockchain/src/header/version.rs
Labels: test

#483 Clippy warnings rush
  chain-impl-mockchain/src/testing/arbitrary/address.rs
  chain-impl-mockchain/src/testing/arbitrary/kind_type.rs
  chain-impl-mockchain/src/testing/arbitrary/output.rs
  chain-impl-mockchain/src/testing/arbitrary/transaction.rs
  chain-impl-mockchain/src/testing/builders/tx_builder.rs
  chain-impl-mockchain/src/testing/data/address.rs
  chain-impl-mockchain/src/testing/gen/vote.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: cleanup

#485 use SmallRng instead of ChaCha for generating test keys
  chain-crypto/Cargo.toml
  chain-crypto/src/testing.rs
Labels: enhancement, test

#487 error on empty keys list in private vote plans
  chain-impl-mockchain/src/testing/e2e/vote_private.rs
  chain-impl-mockchain/src/vote/ledger.rs
Labels: bug

#489 store iterator vs sequential get with different permanent store utilization
  chain-storage/benches/storage.rs
Labels: bench

#486 No need to use format! macro in panic!
  chain-impl-mockchain/src/testing/verifiers/ledger_verifier.rs
Labels: cleanup, test

#492 Remove btree
  Cargo.toml
  btree/.gitignore
  btree/Cargo.toml
  btree/README.md
  btree/benches/benchmark.rs
  btree/doc/design.md
  btree/examples/blockindex.rs
  btree/examples/insertions.txt
  btree/examples/queries.txt
  btree/examples/test.sh
  btree/src/arrayview.rs
  btree/src/btreeindex/backtrack.rs
  btree/src/btreeindex/iter.rs
  btree/src/btreeindex/metadata.rs
  btree/src/btreeindex/mod.rs
  btree/src/btreeindex/node/internal_node.rs
  btree/src/btreeindex/node/leaf_node.rs
  btree/src/btreeindex/node/mod.rs
  btree/src/btreeindex/page_manager.rs
  btree/src/btreeindex/pages.rs
  btree/src/btreeindex/version_management/mod.rs
  btree/src/btreeindex/version_management/transaction.rs
  btree/src/flatfile.rs
  btree/src/lib.rs
  btree/src/mem_page.rs
  btree/src/storage.rs
Labels: cleanup

#493 Implemented EncryptedVote for mock-chain
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/vote/manager.rs
  chain-impl-mockchain/src/vote/mod.rs
  chain-impl-mockchain/src/vote/payload.rs
  chain-impl-mockchain/src/vote/privacy.rs
Labels: enhancement

#488 chain-network: add PullBlocks endpoint to request a range of blocks
  chain-network/proto/node.proto
  chain-network/src/core/server/block.rs
  chain-network/src/grpc/client.rs
  chain-network/src/grpc/server.rs
Labels: enhancement
