Repository input-output-hk/chain-libs, pull requests merged in 2021-05, with the labels that each got.

#558 compile-test benchmarks
  .github/workflows/main.yml
Labels: CI, bench

#561 Changed encryption signature
  chain-vote/src/commitment.rs
  chain-vote/src/committee.rs
  chain-vote/src/encrypted.rs
  chain-vote/src/encryption.rs
  chain-vote/src/gang/mod.rs
  chain-vote/src/gang/p256k1.rs
  chain-vote/src/gang/ristretto255.rs
  chain-vote/src/gargamel.rs
  chain-vote/src/hybrid.rs
  chain-vote/src/lib.rs
  chain-vote/src/macros.rs
  chain-vote/src/shvzk.rs
Labels: design, doc

#563 cover some general things with editorconfig
  .editorconfig
  .github/workflows/editorconfig.yml
  chain-impl-mockchain/doc/format.md
  chain-impl-mockchain/doc/incentives.md
  chain-impl-mockchain/doc/multisig.md
  chain-impl-mockchain/doc/overview.md
  chain-test-utils/Cargo.toml
  chain-time/Cargo.toml
Labels: CI

#566 Fix lints reported by clippy 0.1.52
  chain-impl-mockchain/src/key.rs
  chain-impl-mockchain/src/ledger/pots.rs
  chain-time/src/timeframe.rs
Labels: cleanup

#567 chain-impl-mockchain: Send + Sync for leadership error
  chain-impl-mockchain/src/leadership/mod.rs
Labels: enhancement

#564 Reestructure and review of the unit vector zero knowledge proof
  chain-impl-mockchain/src/vote/payload.rs
  chain-vote/Cargo.toml
  chain-vote/benches/curve.rs
  chain-vote/benches/shvzk.rs
  chain-vote/src/commitment.rs
  chain-vote/src/committee.rs
  chain-vote/src/encryption.rs
  chain-vote/src/gang/p256k1.rs
  chain-vote/src/gang/ristretto255.rs
  chain-vote/src/lib.rs
  chain-vote/src/private_voting/challenge_context.rs
  chain-vote/src/private_voting/messages.rs
  chain-vote/src/private_voting/mod.rs
  chain-vote/src/private_voting/unit_vector_zkp.rs
  chain-vote/src/shvzk.rs
Labels: bug, crypto, enhancement

#568 cleanup test-related dependencies management
  chain-addr/Cargo.toml
  chain-addr/src/lib.rs
  chain-crypto/Cargo.toml
  chain-crypto/src/lib.rs
  chain-crypto/src/sign.rs
  chain-impl-mockchain/Cargo.toml
  chain-impl-mockchain/src/ledger/mod.rs
  chain-impl-mockchain/src/lib.rs
  imhamt/Cargo.toml
Labels: cleanup
