Repository input-output-hk/chain-libs, pull requests merged in 2021-03, with the labels that each got.

#534 chain-vote: fix GroupElement::zero deserialization
  chain-vote/src/gang/p256k1.rs
  chain-vote/src/lib.rs
Labels: bug

#537 Performance fixes and cleanup in vote ledger
  chain-impl-mockchain/src/certificate/vote_plan.rs
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/vote/ledger.rs
  chain-impl-mockchain/src/vote/manager.rs
Labels: cleanup

#540 enable property-test-api in dependencies when it is enabled in a package
  chain-addr/Cargo.toml
  chain-impl-mockchain/Cargo.toml
Labels: enhancement

#543 ledger: allow to apply block in separate steps
  chain-impl-mockchain/src/chaineval.rs
  chain-impl-mockchain/src/header/header.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/multiverse.rs
  chain-impl-mockchain/src/testing/ledger.rs
Labels: enhancement

#529 chain-vote: use faster scalar multiplication encrypted tally construction and decrypted tally verification
  chain-vote/Cargo.toml
  chain-vote/src/gang/p256k1.rs
  chain-vote/src/gargamel.rs
  chain-vote/src/lib.rs
Labels: enhancement

#544 allow governance actions of the same type within a vote plan
  chain-impl-mockchain/src/ledger/governance/parameters.rs
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: bug
