Repository input-output-hk/chain-libs, pull requests merged in 2021-09, with the labels that each got.

#629 expose the valid_transaction_date function to be reusable
  chain-impl-mockchain/src/ledger/check.rs
  chain-impl-mockchain/src/ledger/ledger.rs
Labels: enhancement

#630 Update bech32 dependency to 0.8, fix potential encoding ambiguity
  chain-addr/Cargo.toml
  chain-addr/src/lib.rs
  chain-crypto/Cargo.toml
  chain-crypto/src/bech32.rs
  chain-crypto/src/digest.rs
  chain-crypto/src/hash.rs
  chain-crypto/src/key.rs
  chain-crypto/src/sign.rs
  chain-vote/src/committee.rs
  chain-vote/src/cryptography/elgamal.rs
Labels: dependencies

#638 imhamt: remove nested boxes
  imhamt/src/node/reference.rs
Labels: refactoring

#632 CI: Bump the test timeout to 60 minutes
  .github/workflows/main.yml
Labels: CI

#639 Replace Arc<Box<[T]>> fields with Arc<[T]>
  chain-impl-mockchain/src/leadership/bft.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/setting.rs
Labels: cleanup

#640 Override a clippy lint on Digest::digest
  chain-crypto/src/digest.rs
Labels: cleanup

#642 Fix more dead_code lints
  chain-impl-mockchain/benches/tally.rs
  chain-impl-mockchain/src/leadership/genesis/mod.rs
  chain-impl-mockchain/src/ledger/iter.rs
  chain-impl-mockchain/src/ledger/ledger.rs
  chain-impl-mockchain/src/ledger/recovery.rs
  chain-impl-mockchain/src/ledger/tests/apply_block_tests.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_registration.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/pool_update.rs
  chain-impl-mockchain/src/ledger/tests/certificate_tests/voting.rs
  chain-impl-mockchain/src/ledger/tests/discrimination_tests.rs
  chain-impl-mockchain/src/ledger/tests/initial_funds_tests.rs
  chain-impl-mockchain/src/ledger/tests/ledger_tests.rs
  chain-impl-mockchain/src/ledger/tests/transaction_tests.rs
  chain-impl-mockchain/src/ledger/tests/update_tests.rs
  chain-impl-mockchain/src/testing/arbitrary/config_builder.rs
  chain-impl-mockchain/src/testing/data/wallet.rs
  chain-impl-mockchain/src/testing/e2e/fees.rs
  chain-impl-mockchain/src/testing/e2e/owner_delegation.rs
  chain-impl-mockchain/src/testing/e2e/pool_update.rs
  chain-impl-mockchain/src/testing/e2e/rewards/mod.rs
  chain-impl-mockchain/src/testing/e2e/rewards/tax.rs
  chain-impl-mockchain/src/testing/e2e/stake_distribution.rs
  chain-impl-mockchain/src/testing/e2e/vote_private.rs
  chain-impl-mockchain/src/testing/e2e/vote_public.rs
  chain-impl-mockchain/src/testing/ledger.rs
  chain-impl-mockchain/src/testing/scenario/controller.rs
  chain-impl-mockchain/src/testing/scenario/scenario_builder.rs
  chain-storage/src/permanent_store.rs
  chain-vote/src/committee.rs
Labels: cleanup

#635 chain-time: migrate to proptest and expose proptest APIs
  chain-time/Cargo.toml
  chain-time/src/era.rs
  chain-time/src/lib.rs
  chain-time/src/timeframe.rs
Labels: refactoring, test

#641 chain-crypto: migrate tests from quickcheck to proptest
  .github/workflows/main.yml
  chain-crypto/Cargo.toml
  chain-crypto/src/algorithms/ed25519.rs
  chain-crypto/src/algorithms/ed25519_derive.rs
  chain-crypto/src/algorithms/ed25519_extended.rs
  chain-crypto/src/algorithms/sumed25519/common.rs
  chain-crypto/src/algorithms/sumed25519/mod.rs
  chain-crypto/src/algorithms/sumed25519/sum.rs
  chain-crypto/src/algorithms/vrf/mod.rs
  chain-crypto/src/key.rs
  chain-crypto/src/lib.rs
  chain-crypto/src/testing.rs
Labels: refactoring, test

#634 imhamt: migrate to proptest from quickcheck
  imhamt/Cargo.toml
  imhamt/src/hamt.rs
  imhamt/src/lib.rs
  imhamt/src/node/reference.rs
Labels: refactoring, test

#647 CircleCI: deny warnings and disable incremental
  .circleci/config.yml
Labels: CI

#645 sparse-array: switch to our version of proptest
  sparse-array/Cargo.toml
Labels: dependencies

#646 chain-addr: migrate tests to proptest
  chain-addr/Cargo.toml
  chain-addr/src/lib.rs
  chain-crypto/src/key.rs
  chain-crypto/src/testing.rs
Labels: refactoring
